server:
  port: 9002
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32
#  servlet:
#    context-path: /order


spring:
  application:
    name: dows-order
  profiles:
    include: mysql,mybatis,mvc,redis,alipay
    active: sit
#debug: true
log:
  binlog:
    hosts:
      - name: dxz
        host: sh-cdb-1qjrazc8.sql.tencentcdb.com
        port: 63915
        username: admin
        password: dxzsaas@!
        timeOffset: 1000
